version: '2'
services:
  snowflurry:
    container_name: snowflurry
    build: .
    environment:
      - IN_DOCKER=True
      - SNOWFLURRY_CONFIG_FILE=/secrets/snowflurry.json
    volumes:
      - ./secrets:/secrets
      - ./scripts:/app/scripts
      - ./excel:/excel
    ports:
      - 8501:8501
